pipeline {
  agent none

  stages {
    stage('Back-end Build') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        checkout scm
        sh 'mvn clean install'
        sh 'mvn --version'
      }
    }

    stage('Front-end Build') {
      agent {
        docker { image 'node:24-alpine' } // Use latest stable Node LTS
      }
      steps {
        checkout scm
        sh 'npm install'
        sh 'npm run build'
        sh 'node --version'
      }
    }
  }
}
